/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package no.mesan.miniprosjekt.kommunikasjon.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroAircraft extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroAircraft\",\"namespace\":\"no.mesan.miniprosjekt.kommunikasjon.domain\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"drawing\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.nio.ByteBuffer drawing;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroAircraft() {}

  /**
   * All-args constructor.
   */
  public AvroAircraft(java.lang.CharSequence name, java.nio.ByteBuffer drawing) {
    this.name = name;
    this.drawing = drawing;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return drawing;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: drawing = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'drawing' field.
   */
  public java.nio.ByteBuffer getDrawing() {
    return drawing;
  }

  /**
   * Sets the value of the 'drawing' field.
   * @param value the value to set.
   */
  public void setDrawing(java.nio.ByteBuffer value) {
    this.drawing = value;
  }

  /** Creates a new AvroAircraft RecordBuilder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder newBuilder() {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder();
  }
  
  /** Creates a new AvroAircraft RecordBuilder by copying an existing Builder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder(other);
  }
  
  /** Creates a new AvroAircraft RecordBuilder by copying an existing AvroAircraft instance */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroAircraft instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroAircraft>
    implements org.apache.avro.data.RecordBuilder<AvroAircraft> {

    private java.lang.CharSequence name;
    private java.nio.ByteBuffer drawing;

    /** Creates a new Builder */
    private Builder() {
      super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.drawing)) {
        this.drawing = data().deepCopy(fields()[1].schema(), other.drawing);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroAircraft instance */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft other) {
            super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.drawing)) {
        this.drawing = data().deepCopy(fields()[1].schema(), other.drawing);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'drawing' field */
    public java.nio.ByteBuffer getDrawing() {
      return drawing;
    }
    
    /** Sets the value of the 'drawing' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder setDrawing(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.drawing = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'drawing' field has been set */
    public boolean hasDrawing() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'drawing' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft.Builder clearDrawing() {
      drawing = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroAircraft build() {
      try {
        AvroAircraft record = new AvroAircraft();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.drawing = fieldSetFlags()[1] ? this.drawing : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
