/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package no.mesan.miniprosjekt.kommunikasjon.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroAviationDatas extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroAviationDatas\",\"namespace\":\"no.mesan.miniprosjekt.kommunikasjon.domain\",\"fields\":[{\"name\":\"aviationDatas\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroAviationData\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"accidentNumber\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData> aviationDatas;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroAviationDatas() {}

  /**
   * All-args constructor.
   */
  public AvroAviationDatas(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData> aviationDatas) {
    this.aviationDatas = aviationDatas;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return aviationDatas;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: aviationDatas = (java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'aviationDatas' field.
   */
  public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData> getAviationDatas() {
    return aviationDatas;
  }

  /**
   * Sets the value of the 'aviationDatas' field.
   * @param value the value to set.
   */
  public void setAviationDatas(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData> value) {
    this.aviationDatas = value;
  }

  /** Creates a new AvroAviationDatas RecordBuilder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder newBuilder() {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder();
  }
  
  /** Creates a new AvroAviationDatas RecordBuilder by copying an existing Builder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder(other);
  }
  
  /** Creates a new AvroAviationDatas RecordBuilder by copying an existing AvroAviationDatas instance */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroAviationDatas instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroAviationDatas>
    implements org.apache.avro.data.RecordBuilder<AvroAviationDatas> {

    private java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData> aviationDatas;

    /** Creates a new Builder */
    private Builder() {
      super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.aviationDatas)) {
        this.aviationDatas = data().deepCopy(fields()[0].schema(), other.aviationDatas);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroAviationDatas instance */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas other) {
            super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.SCHEMA$);
      if (isValidValue(fields()[0], other.aviationDatas)) {
        this.aviationDatas = data().deepCopy(fields()[0].schema(), other.aviationDatas);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'aviationDatas' field */
    public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData> getAviationDatas() {
      return aviationDatas;
    }
    
    /** Sets the value of the 'aviationDatas' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder setAviationDatas(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData> value) {
      validate(fields()[0], value);
      this.aviationDatas = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'aviationDatas' field has been set */
    public boolean hasAviationDatas() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'aviationDatas' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationDatas.Builder clearAviationDatas() {
      aviationDatas = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroAviationDatas build() {
      try {
        AvroAviationDatas record = new AvroAviationDatas();
        record.aviationDatas = fieldSetFlags()[0] ? this.aviationDatas : (java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
