/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package no.mesan.miniprosjekt.kommunikasjon.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroOs extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroOs\",\"namespace\":\"no.mesan.miniprosjekt.kommunikasjon.domain\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"system\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.nio.ByteBuffer system;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroOs() {}

  /**
   * All-args constructor.
   */
  public AvroOs(java.lang.CharSequence name, java.nio.ByteBuffer system) {
    this.name = name;
    this.system = system;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return system;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: system = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'system' field.
   */
  public java.nio.ByteBuffer getSystem() {
    return system;
  }

  /**
   * Sets the value of the 'system' field.
   * @param value the value to set.
   */
  public void setSystem(java.nio.ByteBuffer value) {
    this.system = value;
  }

  /** Creates a new AvroOs RecordBuilder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder newBuilder() {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder();
  }
  
  /** Creates a new AvroOs RecordBuilder by copying an existing Builder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder(other);
  }
  
  /** Creates a new AvroOs RecordBuilder by copying an existing AvroOs instance */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroOs instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroOs>
    implements org.apache.avro.data.RecordBuilder<AvroOs> {

    private java.lang.CharSequence name;
    private java.nio.ByteBuffer system;

    /** Creates a new Builder */
    private Builder() {
      super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.system)) {
        this.system = data().deepCopy(fields()[1].schema(), other.system);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroOs instance */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs other) {
            super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.system)) {
        this.system = data().deepCopy(fields()[1].schema(), other.system);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'system' field */
    public java.nio.ByteBuffer getSystem() {
      return system;
    }
    
    /** Sets the value of the 'system' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder setSystem(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.system = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'system' field has been set */
    public boolean hasSystem() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'system' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs.Builder clearSystem() {
      system = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroOs build() {
      try {
        AvroOs record = new AvroOs();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.system = fieldSetFlags()[1] ? this.system : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
