/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package no.mesan.miniprosjekt.kommunikasjon.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroOss extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroOss\",\"namespace\":\"no.mesan.miniprosjekt.kommunikasjon.domain\",\"fields\":[{\"name\":\"oss\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroOs\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"system\",\"type\":\"bytes\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs> oss;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroOss() {}

  /**
   * All-args constructor.
   */
  public AvroOss(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs> oss) {
    this.oss = oss;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return oss;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: oss = (java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'oss' field.
   */
  public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs> getOss() {
    return oss;
  }

  /**
   * Sets the value of the 'oss' field.
   * @param value the value to set.
   */
  public void setOss(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs> value) {
    this.oss = value;
  }

  /** Creates a new AvroOss RecordBuilder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder newBuilder() {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder();
  }
  
  /** Creates a new AvroOss RecordBuilder by copying an existing Builder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder(other);
  }
  
  /** Creates a new AvroOss RecordBuilder by copying an existing AvroOss instance */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroOss instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroOss>
    implements org.apache.avro.data.RecordBuilder<AvroOss> {

    private java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs> oss;

    /** Creates a new Builder */
    private Builder() {
      super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.oss)) {
        this.oss = data().deepCopy(fields()[0].schema(), other.oss);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroOss instance */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss other) {
            super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.SCHEMA$);
      if (isValidValue(fields()[0], other.oss)) {
        this.oss = data().deepCopy(fields()[0].schema(), other.oss);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'oss' field */
    public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs> getOss() {
      return oss;
    }
    
    /** Sets the value of the 'oss' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder setOss(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs> value) {
      validate(fields()[0], value);
      this.oss = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'oss' field has been set */
    public boolean hasOss() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'oss' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroOss.Builder clearOss() {
      oss = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroOss build() {
      try {
        AvroOss record = new AvroOss();
        record.oss = fieldSetFlags()[0] ? this.oss : (java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroOs>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
