/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package no.mesan.miniprosjekt.kommunikasjon.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroAviationData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroAviationData\",\"namespace\":\"no.mesan.miniprosjekt.kommunikasjon.domain\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"accidentNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence accidentNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroAviationData() {}

  /**
   * All-args constructor.
   */
  public AvroAviationData(java.lang.CharSequence id, java.lang.CharSequence accidentNumber) {
    this.id = id;
    this.accidentNumber = accidentNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return accidentNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: accidentNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'accidentNumber' field.
   */
  public java.lang.CharSequence getAccidentNumber() {
    return accidentNumber;
  }

  /**
   * Sets the value of the 'accidentNumber' field.
   * @param value the value to set.
   */
  public void setAccidentNumber(java.lang.CharSequence value) {
    this.accidentNumber = value;
  }

  /** Creates a new AvroAviationData RecordBuilder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder newBuilder() {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder();
  }
  
  /** Creates a new AvroAviationData RecordBuilder by copying an existing Builder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder(other);
  }
  
  /** Creates a new AvroAviationData RecordBuilder by copying an existing AvroAviationData instance */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroAviationData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroAviationData>
    implements org.apache.avro.data.RecordBuilder<AvroAviationData> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence accidentNumber;

    /** Creates a new Builder */
    private Builder() {
      super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accidentNumber)) {
        this.accidentNumber = data().deepCopy(fields()[1].schema(), other.accidentNumber);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroAviationData instance */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData other) {
            super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accidentNumber)) {
        this.accidentNumber = data().deepCopy(fields()[1].schema(), other.accidentNumber);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'accidentNumber' field */
    public java.lang.CharSequence getAccidentNumber() {
      return accidentNumber;
    }
    
    /** Sets the value of the 'accidentNumber' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder setAccidentNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.accidentNumber = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'accidentNumber' field has been set */
    public boolean hasAccidentNumber() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'accidentNumber' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAviationData.Builder clearAccidentNumber() {
      accidentNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroAviationData build() {
      try {
        AvroAviationData record = new AvroAviationData();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.accidentNumber = fieldSetFlags()[1] ? this.accidentNumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
