/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package no.mesan.miniprosjekt.kommunikasjon.domain;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AvroProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroProtocol\",\"namespace\":\"no.mesan.miniprosjekt.kommunikasjon.domain\",\"types\":[{\"type\":\"record\",\"name\":\"AvroAircraft\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"drawing\",\"type\":\"bytes\"}]}],\"messages\":{\"send\":{\"request\":[],\"response\":\"AvroAircraft\"}}}");
  no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft send() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AvroProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = no.mesan.miniprosjekt.kommunikasjon.domain.AvroProtocol.PROTOCOL;
    void send(org.apache.avro.ipc.Callback<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> callback) throws java.io.IOException;
  }
}