/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package no.mesan.miniprosjekt.kommunikasjon.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroAircrafts extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroAircrafts\",\"namespace\":\"no.mesan.miniprosjekt.kommunikasjon.domain\",\"fields\":[{\"name\":\"aircrafts\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroAircraft\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"drawing\",\"type\":\"bytes\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> aircrafts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public AvroAircrafts() {}

  /**
   * All-args constructor.
   */
  public AvroAircrafts(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> aircrafts) {
    this.aircrafts = aircrafts;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return aircrafts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: aircrafts = (java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'aircrafts' field.
   */
  public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> getAircrafts() {
    return aircrafts;
  }

  /**
   * Sets the value of the 'aircrafts' field.
   * @param value the value to set.
   */
  public void setAircrafts(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> value) {
    this.aircrafts = value;
  }

  /** Creates a new AvroAircrafts RecordBuilder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder newBuilder() {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder();
  }
  
  /** Creates a new AvroAircrafts RecordBuilder by copying an existing Builder */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder(other);
  }
  
  /** Creates a new AvroAircrafts RecordBuilder by copying an existing AvroAircrafts instance */
  public static no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts other) {
    return new no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroAircrafts instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroAircrafts>
    implements org.apache.avro.data.RecordBuilder<AvroAircrafts> {

    private java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> aircrafts;

    /** Creates a new Builder */
    private Builder() {
      super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.aircrafts)) {
        this.aircrafts = data().deepCopy(fields()[0].schema(), other.aircrafts);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroAircrafts instance */
    private Builder(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts other) {
            super(no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.SCHEMA$);
      if (isValidValue(fields()[0], other.aircrafts)) {
        this.aircrafts = data().deepCopy(fields()[0].schema(), other.aircrafts);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'aircrafts' field */
    public java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> getAircrafts() {
      return aircrafts;
    }
    
    /** Sets the value of the 'aircrafts' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder setAircrafts(java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft> value) {
      validate(fields()[0], value);
      this.aircrafts = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'aircrafts' field has been set */
    public boolean hasAircrafts() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'aircrafts' field */
    public no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircrafts.Builder clearAircrafts() {
      aircrafts = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroAircrafts build() {
      try {
        AvroAircrafts record = new AvroAircrafts();
        record.aircrafts = fieldSetFlags()[0] ? this.aircrafts : (java.util.List<no.mesan.miniprosjekt.kommunikasjon.domain.AvroAircraft>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
