// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aircraft.proto

package no.mesan.miniprosjekt.kommunikasjon.protobuf;

public final class AircraftProto {
  private AircraftProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string request = 1;
    boolean hasRequest();
    String getRequest();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string request = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private java.lang.Object request_;
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRequest() {
      java.lang.Object ref = request_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          request_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequestBytes() {
      java.lang.Object ref = request_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        request_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      request_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_Request_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        request_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.request_ = request_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequest()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              request_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string request = 1;
      private java.lang.Object request_ = "";
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRequest() {
        java.lang.Object ref = request_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          request_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequest(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        request_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        request_ = getDefaultInstance().getRequest();
        onChanged();
        return this;
      }
      void setRequest(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        request_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.Request)
  }
  
  public interface AircraftMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required bytes drawing = 2;
    boolean hasDrawing();
    com.google.protobuf.ByteString getDrawing();
  }
  public static final class AircraftMessage extends
      com.google.protobuf.GeneratedMessage
      implements AircraftMessageOrBuilder {
    // Use AircraftMessage.newBuilder() to construct.
    private AircraftMessage(Builder builder) {
      super(builder);
    }
    private AircraftMessage(boolean noInit) {}
    
    private static final AircraftMessage defaultInstance;
    public static AircraftMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public AircraftMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes drawing = 2;
    public static final int DRAWING_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString drawing_;
    public boolean hasDrawing() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getDrawing() {
      return drawing_;
    }
    
    private void initFields() {
      name_ = "";
      drawing_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDrawing()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, drawing_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, drawing_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessage_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        drawing_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.drawing_ = drawing_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDrawing()) {
          setDrawing(other.getDrawing());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasDrawing()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              drawing_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required bytes drawing = 2;
      private com.google.protobuf.ByteString drawing_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasDrawing() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getDrawing() {
        return drawing_;
      }
      public Builder setDrawing(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        drawing_ = value;
        onChanged();
        return this;
      }
      public Builder clearDrawing() {
        bitField0_ = (bitField0_ & ~0x00000002);
        drawing_ = getDefaultInstance().getDrawing();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.AircraftMessage)
    }
    
    static {
      defaultInstance = new AircraftMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.AircraftMessage)
  }
  
  public interface AircraftMessagesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protobuf.AircraftMessage aircraftmessage = 1;
    java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage> 
        getAircraftmessageList();
    no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage getAircraftmessage(int index);
    int getAircraftmessageCount();
    java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder> 
        getAircraftmessageOrBuilderList();
    no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder getAircraftmessageOrBuilder(
        int index);
  }
  public static final class AircraftMessages extends
      com.google.protobuf.GeneratedMessage
      implements AircraftMessagesOrBuilder {
    // Use AircraftMessages.newBuilder() to construct.
    private AircraftMessages(Builder builder) {
      super(builder);
    }
    private AircraftMessages(boolean noInit) {}
    
    private static final AircraftMessages defaultInstance;
    public static AircraftMessages getDefaultInstance() {
      return defaultInstance;
    }
    
    public AircraftMessages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessages_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessages_fieldAccessorTable;
    }
    
    // repeated .protobuf.AircraftMessage aircraftmessage = 1;
    public static final int AIRCRAFTMESSAGE_FIELD_NUMBER = 1;
    private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage> aircraftmessage_;
    public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage> getAircraftmessageList() {
      return aircraftmessage_;
    }
    public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder> 
        getAircraftmessageOrBuilderList() {
      return aircraftmessage_;
    }
    public int getAircraftmessageCount() {
      return aircraftmessage_.size();
    }
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage getAircraftmessage(int index) {
      return aircraftmessage_.get(index);
    }
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder getAircraftmessageOrBuilder(
        int index) {
      return aircraftmessage_.get(index);
    }
    
    private void initFields() {
      aircraftmessage_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getAircraftmessageCount(); i++) {
        if (!getAircraftmessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < aircraftmessage_.size(); i++) {
        output.writeMessage(1, aircraftmessage_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < aircraftmessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, aircraftmessage_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessages_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.internal_static_protobuf_AircraftMessages_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAircraftmessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (aircraftmessageBuilder_ == null) {
          aircraftmessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          aircraftmessageBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages(this);
        int from_bitField0_ = bitField0_;
        if (aircraftmessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            aircraftmessage_ = java.util.Collections.unmodifiableList(aircraftmessage_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.aircraftmessage_ = aircraftmessage_;
        } else {
          result.aircraftmessage_ = aircraftmessageBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages.getDefaultInstance()) return this;
        if (aircraftmessageBuilder_ == null) {
          if (!other.aircraftmessage_.isEmpty()) {
            if (aircraftmessage_.isEmpty()) {
              aircraftmessage_ = other.aircraftmessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAircraftmessageIsMutable();
              aircraftmessage_.addAll(other.aircraftmessage_);
            }
            onChanged();
          }
        } else {
          if (!other.aircraftmessage_.isEmpty()) {
            if (aircraftmessageBuilder_.isEmpty()) {
              aircraftmessageBuilder_.dispose();
              aircraftmessageBuilder_ = null;
              aircraftmessage_ = other.aircraftmessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
              aircraftmessageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAircraftmessageFieldBuilder() : null;
            } else {
              aircraftmessageBuilder_.addAllMessages(other.aircraftmessage_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getAircraftmessageCount(); i++) {
          if (!getAircraftmessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder subBuilder = no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAircraftmessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protobuf.AircraftMessage aircraftmessage = 1;
      private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage> aircraftmessage_ =
        java.util.Collections.emptyList();
      private void ensureAircraftmessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          aircraftmessage_ = new java.util.ArrayList<no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage>(aircraftmessage_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder> aircraftmessageBuilder_;
      
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage> getAircraftmessageList() {
        if (aircraftmessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(aircraftmessage_);
        } else {
          return aircraftmessageBuilder_.getMessageList();
        }
      }
      public int getAircraftmessageCount() {
        if (aircraftmessageBuilder_ == null) {
          return aircraftmessage_.size();
        } else {
          return aircraftmessageBuilder_.getCount();
        }
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage getAircraftmessage(int index) {
        if (aircraftmessageBuilder_ == null) {
          return aircraftmessage_.get(index);
        } else {
          return aircraftmessageBuilder_.getMessage(index);
        }
      }
      public Builder setAircraftmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage value) {
        if (aircraftmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAircraftmessageIsMutable();
          aircraftmessage_.set(index, value);
          onChanged();
        } else {
          aircraftmessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAircraftmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder builderForValue) {
        if (aircraftmessageBuilder_ == null) {
          ensureAircraftmessageIsMutable();
          aircraftmessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          aircraftmessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAircraftmessage(no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage value) {
        if (aircraftmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAircraftmessageIsMutable();
          aircraftmessage_.add(value);
          onChanged();
        } else {
          aircraftmessageBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAircraftmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage value) {
        if (aircraftmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAircraftmessageIsMutable();
          aircraftmessage_.add(index, value);
          onChanged();
        } else {
          aircraftmessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAircraftmessage(
          no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder builderForValue) {
        if (aircraftmessageBuilder_ == null) {
          ensureAircraftmessageIsMutable();
          aircraftmessage_.add(builderForValue.build());
          onChanged();
        } else {
          aircraftmessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAircraftmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder builderForValue) {
        if (aircraftmessageBuilder_ == null) {
          ensureAircraftmessageIsMutable();
          aircraftmessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          aircraftmessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAircraftmessage(
          java.lang.Iterable<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage> values) {
        if (aircraftmessageBuilder_ == null) {
          ensureAircraftmessageIsMutable();
          super.addAll(values, aircraftmessage_);
          onChanged();
        } else {
          aircraftmessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAircraftmessage() {
        if (aircraftmessageBuilder_ == null) {
          aircraftmessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          aircraftmessageBuilder_.clear();
        }
        return this;
      }
      public Builder removeAircraftmessage(int index) {
        if (aircraftmessageBuilder_ == null) {
          ensureAircraftmessageIsMutable();
          aircraftmessage_.remove(index);
          onChanged();
        } else {
          aircraftmessageBuilder_.remove(index);
        }
        return this;
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder getAircraftmessageBuilder(
          int index) {
        return getAircraftmessageFieldBuilder().getBuilder(index);
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder getAircraftmessageOrBuilder(
          int index) {
        if (aircraftmessageBuilder_ == null) {
          return aircraftmessage_.get(index);  } else {
          return aircraftmessageBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder> 
           getAircraftmessageOrBuilderList() {
        if (aircraftmessageBuilder_ != null) {
          return aircraftmessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(aircraftmessage_);
        }
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder addAircraftmessageBuilder() {
        return getAircraftmessageFieldBuilder().addBuilder(
            no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.getDefaultInstance());
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder addAircraftmessageBuilder(
          int index) {
        return getAircraftmessageFieldBuilder().addBuilder(
            index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.getDefaultInstance());
      }
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder> 
           getAircraftmessageBuilderList() {
        return getAircraftmessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder> 
          getAircraftmessageFieldBuilder() {
        if (aircraftmessageBuilder_ == null) {
          aircraftmessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessageOrBuilder>(
                  aircraftmessage_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          aircraftmessage_ = null;
        }
        return aircraftmessageBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.AircraftMessages)
    }
    
    static {
      defaultInstance = new AircraftMessages(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.AircraftMessages)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_AircraftMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_AircraftMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_AircraftMessages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_AircraftMessages_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016aircraft.proto\022\010protobuf\"\032\n\007Request\022\017\n" +
      "\007request\030\001 \002(\t\"0\n\017AircraftMessage\022\014\n\004nam" +
      "e\030\001 \002(\t\022\017\n\007drawing\030\002 \002(\014\"F\n\020AircraftMess" +
      "ages\0222\n\017aircraftmessage\030\001 \003(\0132\031.protobuf" +
      ".AircraftMessageB?\n,no.mesan.miniprosjek" +
      "t.kommunikasjon.protobufB\rAircraftProtoH" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Request_descriptor,
              new java.lang.String[] { "Request", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.Request.Builder.class);
          internal_static_protobuf_AircraftMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_AircraftMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_AircraftMessage_descriptor,
              new java.lang.String[] { "Name", "Drawing", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessage.Builder.class);
          internal_static_protobuf_AircraftMessages_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protobuf_AircraftMessages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_AircraftMessages_descriptor,
              new java.lang.String[] { "Aircraftmessage", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AircraftProto.AircraftMessages.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
