// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aviationdata.proto

package no.mesan.miniprosjekt.kommunikasjon.protobuf;

public final class AviationDataProto {
  private AviationDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string request = 1;
    boolean hasRequest();
    String getRequest();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string request = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private java.lang.Object request_;
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRequest() {
      java.lang.Object ref = request_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          request_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequestBytes() {
      java.lang.Object ref = request_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        request_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      request_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_Request_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        request_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.request_ = request_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequest()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              request_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string request = 1;
      private java.lang.Object request_ = "";
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRequest() {
        java.lang.Object ref = request_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          request_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequest(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        request_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        request_ = getDefaultInstance().getRequest();
        onChanged();
        return this;
      }
      void setRequest(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        request_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.Request)
  }
  
  public interface AviationDataMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string accidentnumber = 2;
    boolean hasAccidentnumber();
    String getAccidentnumber();
  }
  public static final class AviationDataMessage extends
      com.google.protobuf.GeneratedMessage
      implements AviationDataMessageOrBuilder {
    // Use AviationDataMessage.newBuilder() to construct.
    private AviationDataMessage(Builder builder) {
      super(builder);
    }
    private AviationDataMessage(boolean noInit) {}
    
    private static final AviationDataMessage defaultInstance;
    public static AviationDataMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public AviationDataMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string accidentnumber = 2;
    public static final int ACCIDENTNUMBER_FIELD_NUMBER = 2;
    private java.lang.Object accidentnumber_;
    public boolean hasAccidentnumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAccidentnumber() {
      java.lang.Object ref = accidentnumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accidentnumber_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccidentnumberBytes() {
      java.lang.Object ref = accidentnumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accidentnumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      accidentnumber_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccidentnumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccidentnumberBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccidentnumberBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        accidentnumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accidentnumber_ = accidentnumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAccidentnumber()) {
          setAccidentnumber(other.getAccidentnumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAccidentnumber()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accidentnumber_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string accidentnumber = 2;
      private java.lang.Object accidentnumber_ = "";
      public boolean hasAccidentnumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAccidentnumber() {
        java.lang.Object ref = accidentnumber_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accidentnumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccidentnumber(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accidentnumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccidentnumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accidentnumber_ = getDefaultInstance().getAccidentnumber();
        onChanged();
        return this;
      }
      void setAccidentnumber(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        accidentnumber_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.AviationDataMessage)
    }
    
    static {
      defaultInstance = new AviationDataMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.AviationDataMessage)
  }
  
  public interface AviationDataMessagesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protobuf.AviationDataMessage aviationdatamessage = 1;
    java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage> 
        getAviationdatamessageList();
    no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage getAviationdatamessage(int index);
    int getAviationdatamessageCount();
    java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder> 
        getAviationdatamessageOrBuilderList();
    no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder getAviationdatamessageOrBuilder(
        int index);
  }
  public static final class AviationDataMessages extends
      com.google.protobuf.GeneratedMessage
      implements AviationDataMessagesOrBuilder {
    // Use AviationDataMessages.newBuilder() to construct.
    private AviationDataMessages(Builder builder) {
      super(builder);
    }
    private AviationDataMessages(boolean noInit) {}
    
    private static final AviationDataMessages defaultInstance;
    public static AviationDataMessages getDefaultInstance() {
      return defaultInstance;
    }
    
    public AviationDataMessages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessages_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessages_fieldAccessorTable;
    }
    
    // repeated .protobuf.AviationDataMessage aviationdatamessage = 1;
    public static final int AVIATIONDATAMESSAGE_FIELD_NUMBER = 1;
    private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage> aviationdatamessage_;
    public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage> getAviationdatamessageList() {
      return aviationdatamessage_;
    }
    public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder> 
        getAviationdatamessageOrBuilderList() {
      return aviationdatamessage_;
    }
    public int getAviationdatamessageCount() {
      return aviationdatamessage_.size();
    }
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage getAviationdatamessage(int index) {
      return aviationdatamessage_.get(index);
    }
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder getAviationdatamessageOrBuilder(
        int index) {
      return aviationdatamessage_.get(index);
    }
    
    private void initFields() {
      aviationdatamessage_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getAviationdatamessageCount(); i++) {
        if (!getAviationdatamessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < aviationdatamessage_.size(); i++) {
        output.writeMessage(1, aviationdatamessage_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < aviationdatamessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, aviationdatamessage_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessages_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessages_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAviationdatamessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (aviationdatamessageBuilder_ == null) {
          aviationdatamessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          aviationdatamessageBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages(this);
        int from_bitField0_ = bitField0_;
        if (aviationdatamessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            aviationdatamessage_ = java.util.Collections.unmodifiableList(aviationdatamessage_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.aviationdatamessage_ = aviationdatamessage_;
        } else {
          result.aviationdatamessage_ = aviationdatamessageBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages.getDefaultInstance()) return this;
        if (aviationdatamessageBuilder_ == null) {
          if (!other.aviationdatamessage_.isEmpty()) {
            if (aviationdatamessage_.isEmpty()) {
              aviationdatamessage_ = other.aviationdatamessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAviationdatamessageIsMutable();
              aviationdatamessage_.addAll(other.aviationdatamessage_);
            }
            onChanged();
          }
        } else {
          if (!other.aviationdatamessage_.isEmpty()) {
            if (aviationdatamessageBuilder_.isEmpty()) {
              aviationdatamessageBuilder_.dispose();
              aviationdatamessageBuilder_ = null;
              aviationdatamessage_ = other.aviationdatamessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
              aviationdatamessageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAviationdatamessageFieldBuilder() : null;
            } else {
              aviationdatamessageBuilder_.addAllMessages(other.aviationdatamessage_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getAviationdatamessageCount(); i++) {
          if (!getAviationdatamessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder subBuilder = no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAviationdatamessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protobuf.AviationDataMessage aviationdatamessage = 1;
      private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage> aviationdatamessage_ =
        java.util.Collections.emptyList();
      private void ensureAviationdatamessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          aviationdatamessage_ = new java.util.ArrayList<no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage>(aviationdatamessage_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder> aviationdatamessageBuilder_;
      
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage> getAviationdatamessageList() {
        if (aviationdatamessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(aviationdatamessage_);
        } else {
          return aviationdatamessageBuilder_.getMessageList();
        }
      }
      public int getAviationdatamessageCount() {
        if (aviationdatamessageBuilder_ == null) {
          return aviationdatamessage_.size();
        } else {
          return aviationdatamessageBuilder_.getCount();
        }
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage getAviationdatamessage(int index) {
        if (aviationdatamessageBuilder_ == null) {
          return aviationdatamessage_.get(index);
        } else {
          return aviationdatamessageBuilder_.getMessage(index);
        }
      }
      public Builder setAviationdatamessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage value) {
        if (aviationdatamessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAviationdatamessageIsMutable();
          aviationdatamessage_.set(index, value);
          onChanged();
        } else {
          aviationdatamessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAviationdatamessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder builderForValue) {
        if (aviationdatamessageBuilder_ == null) {
          ensureAviationdatamessageIsMutable();
          aviationdatamessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          aviationdatamessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAviationdatamessage(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage value) {
        if (aviationdatamessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAviationdatamessageIsMutable();
          aviationdatamessage_.add(value);
          onChanged();
        } else {
          aviationdatamessageBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAviationdatamessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage value) {
        if (aviationdatamessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAviationdatamessageIsMutable();
          aviationdatamessage_.add(index, value);
          onChanged();
        } else {
          aviationdatamessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAviationdatamessage(
          no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder builderForValue) {
        if (aviationdatamessageBuilder_ == null) {
          ensureAviationdatamessageIsMutable();
          aviationdatamessage_.add(builderForValue.build());
          onChanged();
        } else {
          aviationdatamessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAviationdatamessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder builderForValue) {
        if (aviationdatamessageBuilder_ == null) {
          ensureAviationdatamessageIsMutable();
          aviationdatamessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          aviationdatamessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAviationdatamessage(
          java.lang.Iterable<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage> values) {
        if (aviationdatamessageBuilder_ == null) {
          ensureAviationdatamessageIsMutable();
          super.addAll(values, aviationdatamessage_);
          onChanged();
        } else {
          aviationdatamessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAviationdatamessage() {
        if (aviationdatamessageBuilder_ == null) {
          aviationdatamessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          aviationdatamessageBuilder_.clear();
        }
        return this;
      }
      public Builder removeAviationdatamessage(int index) {
        if (aviationdatamessageBuilder_ == null) {
          ensureAviationdatamessageIsMutable();
          aviationdatamessage_.remove(index);
          onChanged();
        } else {
          aviationdatamessageBuilder_.remove(index);
        }
        return this;
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder getAviationdatamessageBuilder(
          int index) {
        return getAviationdatamessageFieldBuilder().getBuilder(index);
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder getAviationdatamessageOrBuilder(
          int index) {
        if (aviationdatamessageBuilder_ == null) {
          return aviationdatamessage_.get(index);  } else {
          return aviationdatamessageBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder> 
           getAviationdatamessageOrBuilderList() {
        if (aviationdatamessageBuilder_ != null) {
          return aviationdatamessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(aviationdatamessage_);
        }
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder addAviationdatamessageBuilder() {
        return getAviationdatamessageFieldBuilder().addBuilder(
            no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.getDefaultInstance());
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder addAviationdatamessageBuilder(
          int index) {
        return getAviationdatamessageFieldBuilder().addBuilder(
            index, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.getDefaultInstance());
      }
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder> 
           getAviationdatamessageBuilderList() {
        return getAviationdatamessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder> 
          getAviationdatamessageFieldBuilder() {
        if (aviationdatamessageBuilder_ == null) {
          aviationdatamessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder>(
                  aviationdatamessage_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          aviationdatamessage_ = null;
        }
        return aviationdatamessageBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.AviationDataMessages)
    }
    
    static {
      defaultInstance = new AviationDataMessages(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.AviationDataMessages)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_AviationDataMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_AviationDataMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_AviationDataMessages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_AviationDataMessages_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022aviationdata.proto\022\010protobuf\"\032\n\007Reques" +
      "t\022\017\n\007request\030\001 \002(\t\"9\n\023AviationDataMessag" +
      "e\022\n\n\002id\030\001 \002(\t\022\026\n\016accidentnumber\030\002 \002(\t\"R\n" +
      "\024AviationDataMessages\022:\n\023aviationdatames" +
      "sage\030\001 \003(\0132\035.protobuf.AviationDataMessag" +
      "eBC\n,no.mesan.miniprosjekt.kommunikasjon" +
      ".protobufB\021AviationDataProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Request_descriptor,
              new java.lang.String[] { "Request", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.Request.Builder.class);
          internal_static_protobuf_AviationDataMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_AviationDataMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_AviationDataMessage_descriptor,
              new java.lang.String[] { "Id", "Accidentnumber", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder.class);
          internal_static_protobuf_AviationDataMessages_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protobuf_AviationDataMessages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_AviationDataMessages_descriptor,
              new java.lang.String[] { "Aviationdatamessage", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessages.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
