// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aviationdata.proto

package no.mesan.miniprosjekt.kommunikasjon.protobuf;

public final class AviationDataProto {
  private AviationDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AviationDataMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string accidentnumber = 2;
    /**
     * <code>required string accidentnumber = 2;</code>
     */
    boolean hasAccidentnumber();
    /**
     * <code>required string accidentnumber = 2;</code>
     */
    java.lang.String getAccidentnumber();
    /**
     * <code>required string accidentnumber = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccidentnumberBytes();
  }
  /**
   * Protobuf type {@code protobuf.AviationDataMessage}
   */
  public static final class AviationDataMessage extends
      com.google.protobuf.GeneratedMessage
      implements AviationDataMessageOrBuilder {
    // Use AviationDataMessage.newBuilder() to construct.
    private AviationDataMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AviationDataMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AviationDataMessage defaultInstance;
    public static AviationDataMessage getDefaultInstance() {
      return defaultInstance;
    }

    public AviationDataMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AviationDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accidentnumber_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.class, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<AviationDataMessage> PARSER =
        new com.google.protobuf.AbstractParser<AviationDataMessage>() {
      public AviationDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AviationDataMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AviationDataMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string accidentnumber = 2;
    public static final int ACCIDENTNUMBER_FIELD_NUMBER = 2;
    private java.lang.Object accidentnumber_;
    /**
     * <code>required string accidentnumber = 2;</code>
     */
    public boolean hasAccidentnumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string accidentnumber = 2;</code>
     */
    public java.lang.String getAccidentnumber() {
      java.lang.Object ref = accidentnumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accidentnumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string accidentnumber = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccidentnumberBytes() {
      java.lang.Object ref = accidentnumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accidentnumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      accidentnumber_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccidentnumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccidentnumberBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccidentnumberBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.AviationDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.class, no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.Builder.class);
      }

      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        accidentnumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.internal_static_protobuf_AviationDataMessage_descriptor;
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.getDefaultInstance();
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accidentnumber_ = accidentnumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasAccidentnumber()) {
          bitField0_ |= 0x00000002;
          accidentnumber_ = other.accidentnumber_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAccidentnumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (no.mesan.miniprosjekt.kommunikasjon.protobuf.AviationDataProto.AviationDataMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string accidentnumber = 2;
      private java.lang.Object accidentnumber_ = "";
      /**
       * <code>required string accidentnumber = 2;</code>
       */
      public boolean hasAccidentnumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string accidentnumber = 2;</code>
       */
      public java.lang.String getAccidentnumber() {
        java.lang.Object ref = accidentnumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accidentnumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string accidentnumber = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccidentnumberBytes() {
        java.lang.Object ref = accidentnumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accidentnumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string accidentnumber = 2;</code>
       */
      public Builder setAccidentnumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accidentnumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string accidentnumber = 2;</code>
       */
      public Builder clearAccidentnumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accidentnumber_ = getDefaultInstance().getAccidentnumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string accidentnumber = 2;</code>
       */
      public Builder setAccidentnumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accidentnumber_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.AviationDataMessage)
    }

    static {
      defaultInstance = new AviationDataMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.AviationDataMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_AviationDataMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_AviationDataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022aviationdata.proto\022\010protobuf\"9\n\023Aviati" +
      "onDataMessage\022\n\n\002id\030\001 \002(\t\022\026\n\016accidentnum" +
      "ber\030\002 \002(\tBA\n,no.mesan.miniprosjekt.kommu" +
      "nikasjon.protobufB\021AviationDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_AviationDataMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_AviationDataMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_AviationDataMessage_descriptor,
              new java.lang.String[] { "Id", "Accidentnumber", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
