// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: os.proto

package no.mesan.miniprosjekt.kommunikasjon.protobuf;

public final class OsProto {
  private OsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OsMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required bytes system = 2;
    /**
     * <code>required bytes system = 2;</code>
     */
    boolean hasSystem();
    /**
     * <code>required bytes system = 2;</code>
     */
    com.google.protobuf.ByteString getSystem();
  }
  /**
   * Protobuf type {@code protobuf.OsMessage}
   */
  public static final class OsMessage extends
      com.google.protobuf.GeneratedMessage
      implements OsMessageOrBuilder {
    // Use OsMessage.newBuilder() to construct.
    private OsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OsMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OsMessage defaultInstance;
    public static OsMessage getDefaultInstance() {
      return defaultInstance;
    }

    public OsMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OsMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              system_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.class, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<OsMessage> PARSER =
        new com.google.protobuf.AbstractParser<OsMessage>() {
      public OsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OsMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OsMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes system = 2;
    public static final int SYSTEM_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString system_;
    /**
     * <code>required bytes system = 2;</code>
     */
    public boolean hasSystem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes system = 2;</code>
     */
    public com.google.protobuf.ByteString getSystem() {
      return system_;
    }

    private void initFields() {
      name_ = "";
      system_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSystem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, system_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, system_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.OsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.class, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder.class);
      }

      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        system_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_descriptor;
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance();
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.system_ = system_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSystem()) {
          setSystem(other.getSystem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasSystem()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required bytes system = 2;
      private com.google.protobuf.ByteString system_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes system = 2;</code>
       */
      public boolean hasSystem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes system = 2;</code>
       */
      public com.google.protobuf.ByteString getSystem() {
        return system_;
      }
      /**
       * <code>required bytes system = 2;</code>
       */
      public Builder setSystem(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        system_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes system = 2;</code>
       */
      public Builder clearSystem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        system_ = getDefaultInstance().getSystem();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.OsMessage)
    }

    static {
      defaultInstance = new OsMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.OsMessage)
  }

  public interface OssMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protobuf.OsMessage osmessage = 1;
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> 
        getOsmessageList();
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getOsmessage(int index);
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    int getOsmessageCount();
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
        getOsmessageOrBuilderList();
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder getOsmessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.OssMessage}
   */
  public static final class OssMessage extends
      com.google.protobuf.GeneratedMessage
      implements OssMessageOrBuilder {
    // Use OssMessage.newBuilder() to construct.
    private OssMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OssMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OssMessage defaultInstance;
    public static OssMessage getDefaultInstance() {
      return defaultInstance;
    }

    public OssMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OssMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                osmessage_ = new java.util.ArrayList<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              osmessage_.add(input.readMessage(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          osmessage_ = java.util.Collections.unmodifiableList(osmessage_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OssMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OssMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage.class, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<OssMessage> PARSER =
        new com.google.protobuf.AbstractParser<OssMessage>() {
      public OssMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OssMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OssMessage> getParserForType() {
      return PARSER;
    }

    // repeated .protobuf.OsMessage osmessage = 1;
    public static final int OSMESSAGE_FIELD_NUMBER = 1;
    private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> osmessage_;
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> getOsmessageList() {
      return osmessage_;
    }
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
        getOsmessageOrBuilderList() {
      return osmessage_;
    }
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    public int getOsmessageCount() {
      return osmessage_.size();
    }
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getOsmessage(int index) {
      return osmessage_.get(index);
    }
    /**
     * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
     */
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder getOsmessageOrBuilder(
        int index) {
      return osmessage_.get(index);
    }

    private void initFields() {
      osmessage_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getOsmessageCount(); i++) {
        if (!getOsmessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < osmessage_.size(); i++) {
        output.writeMessage(1, osmessage_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < osmessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, osmessage_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.OssMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OssMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OssMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage.class, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage.Builder.class);
      }

      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOsmessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (osmessageBuilder_ == null) {
          osmessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          osmessageBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OssMessage_descriptor;
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage.getDefaultInstance();
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage(this);
        int from_bitField0_ = bitField0_;
        if (osmessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            osmessage_ = java.util.Collections.unmodifiableList(osmessage_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.osmessage_ = osmessage_;
        } else {
          result.osmessage_ = osmessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage.getDefaultInstance()) return this;
        if (osmessageBuilder_ == null) {
          if (!other.osmessage_.isEmpty()) {
            if (osmessage_.isEmpty()) {
              osmessage_ = other.osmessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOsmessageIsMutable();
              osmessage_.addAll(other.osmessage_);
            }
            onChanged();
          }
        } else {
          if (!other.osmessage_.isEmpty()) {
            if (osmessageBuilder_.isEmpty()) {
              osmessageBuilder_.dispose();
              osmessageBuilder_ = null;
              osmessage_ = other.osmessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
              osmessageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOsmessageFieldBuilder() : null;
            } else {
              osmessageBuilder_.addAllMessages(other.osmessage_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getOsmessageCount(); i++) {
          if (!getOsmessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OssMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protobuf.OsMessage osmessage = 1;
      private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> osmessage_ =
        java.util.Collections.emptyList();
      private void ensureOsmessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          osmessage_ = new java.util.ArrayList<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage>(osmessage_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> osmessageBuilder_;

      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> getOsmessageList() {
        if (osmessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(osmessage_);
        } else {
          return osmessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public int getOsmessageCount() {
        if (osmessageBuilder_ == null) {
          return osmessage_.size();
        } else {
          return osmessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getOsmessage(int index) {
        if (osmessageBuilder_ == null) {
          return osmessage_.get(index);
        } else {
          return osmessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder setOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage value) {
        if (osmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOsmessageIsMutable();
          osmessage_.set(index, value);
          onChanged();
        } else {
          osmessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder setOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder builderForValue) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          osmessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder addOsmessage(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage value) {
        if (osmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOsmessageIsMutable();
          osmessage_.add(value);
          onChanged();
        } else {
          osmessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder addOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage value) {
        if (osmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOsmessageIsMutable();
          osmessage_.add(index, value);
          onChanged();
        } else {
          osmessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder addOsmessage(
          no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder builderForValue) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.add(builderForValue.build());
          onChanged();
        } else {
          osmessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder addOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder builderForValue) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          osmessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder addAllOsmessage(
          java.lang.Iterable<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> values) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          super.addAll(values, osmessage_);
          onChanged();
        } else {
          osmessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder clearOsmessage() {
        if (osmessageBuilder_ == null) {
          osmessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          osmessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public Builder removeOsmessage(int index) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.remove(index);
          onChanged();
        } else {
          osmessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder getOsmessageBuilder(
          int index) {
        return getOsmessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder getOsmessageOrBuilder(
          int index) {
        if (osmessageBuilder_ == null) {
          return osmessage_.get(index);  } else {
          return osmessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
           getOsmessageOrBuilderList() {
        if (osmessageBuilder_ != null) {
          return osmessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(osmessage_);
        }
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder addOsmessageBuilder() {
        return getOsmessageFieldBuilder().addBuilder(
            no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder addOsmessageBuilder(
          int index) {
        return getOsmessageFieldBuilder().addBuilder(
            index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.OsMessage osmessage = 1;</code>
       */
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder> 
           getOsmessageBuilderList() {
        return getOsmessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
          getOsmessageFieldBuilder() {
        if (osmessageBuilder_ == null) {
          osmessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder>(
                  osmessage_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          osmessage_ = null;
        }
        return osmessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.OssMessage)
    }

    static {
      defaultInstance = new OssMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.OssMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_OsMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_OsMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_OssMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_OssMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010os.proto\022\010protobuf\")\n\tOsMessage\022\014\n\004nam" +
      "e\030\001 \002(\t\022\016\n\006system\030\002 \002(\014\"4\n\nOssMessage\022&\n" +
      "\tosmessage\030\001 \003(\0132\023.protobuf.OsMessageB7\n" +
      ",no.mesan.miniprosjekt.kommunikasjon.pro" +
      "tobufB\007OsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_OsMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_OsMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_OsMessage_descriptor,
              new java.lang.String[] { "Name", "System", });
          internal_static_protobuf_OssMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_OssMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_OssMessage_descriptor,
              new java.lang.String[] { "Osmessage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
