// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: os.proto

package no.mesan.miniprosjekt.kommunikasjon.protobuf;

public final class OsProto {
  private OsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string request = 1;
    boolean hasRequest();
    String getRequest();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string request = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private java.lang.Object request_;
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRequest() {
      java.lang.Object ref = request_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          request_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequestBytes() {
      java.lang.Object ref = request_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        request_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      request_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_Request_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        request_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.request_ = request_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequest()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              request_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string request = 1;
      private java.lang.Object request_ = "";
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRequest() {
        java.lang.Object ref = request_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          request_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequest(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        request_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        request_ = getDefaultInstance().getRequest();
        onChanged();
        return this;
      }
      void setRequest(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        request_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.Request)
  }
  
  public interface OsMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required bytes system = 2;
    boolean hasSystem();
    com.google.protobuf.ByteString getSystem();
  }
  public static final class OsMessage extends
      com.google.protobuf.GeneratedMessage
      implements OsMessageOrBuilder {
    // Use OsMessage.newBuilder() to construct.
    private OsMessage(Builder builder) {
      super(builder);
    }
    private OsMessage(boolean noInit) {}
    
    private static final OsMessage defaultInstance;
    public static OsMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public OsMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes system = 2;
    public static final int SYSTEM_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString system_;
    public boolean hasSystem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getSystem() {
      return system_;
    }
    
    private void initFields() {
      name_ = "";
      system_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSystem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, system_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, system_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessage_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        system_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.system_ = system_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasSystem()) {
          setSystem(other.getSystem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasSystem()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              system_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required bytes system = 2;
      private com.google.protobuf.ByteString system_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasSystem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getSystem() {
        return system_;
      }
      public Builder setSystem(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        system_ = value;
        onChanged();
        return this;
      }
      public Builder clearSystem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        system_ = getDefaultInstance().getSystem();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.OsMessage)
    }
    
    static {
      defaultInstance = new OsMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.OsMessage)
  }
  
  public interface OsMessagesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protobuf.OsMessage osmessage = 1;
    java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> 
        getOsmessageList();
    no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getOsmessage(int index);
    int getOsmessageCount();
    java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
        getOsmessageOrBuilderList();
    no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder getOsmessageOrBuilder(
        int index);
  }
  public static final class OsMessages extends
      com.google.protobuf.GeneratedMessage
      implements OsMessagesOrBuilder {
    // Use OsMessages.newBuilder() to construct.
    private OsMessages(Builder builder) {
      super(builder);
    }
    private OsMessages(boolean noInit) {}
    
    private static final OsMessages defaultInstance;
    public static OsMessages getDefaultInstance() {
      return defaultInstance;
    }
    
    public OsMessages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessages_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessages_fieldAccessorTable;
    }
    
    // repeated .protobuf.OsMessage osmessage = 1;
    public static final int OSMESSAGE_FIELD_NUMBER = 1;
    private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> osmessage_;
    public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> getOsmessageList() {
      return osmessage_;
    }
    public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
        getOsmessageOrBuilderList() {
      return osmessage_;
    }
    public int getOsmessageCount() {
      return osmessage_.size();
    }
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getOsmessage(int index) {
      return osmessage_.get(index);
    }
    public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder getOsmessageOrBuilder(
        int index) {
      return osmessage_.get(index);
    }
    
    private void initFields() {
      osmessage_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getOsmessageCount(); i++) {
        if (!getOsmessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < osmessage_.size(); i++) {
        output.writeMessage(1, osmessage_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < osmessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, osmessage_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessages_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.internal_static_protobuf_OsMessages_fieldAccessorTable;
      }
      
      // Construct using no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOsmessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (osmessageBuilder_ == null) {
          osmessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          osmessageBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages.getDescriptor();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages getDefaultInstanceForType() {
        return no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages.getDefaultInstance();
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages build() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages buildPartial() {
        no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages result = new no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages(this);
        int from_bitField0_ = bitField0_;
        if (osmessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            osmessage_ = java.util.Collections.unmodifiableList(osmessage_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.osmessage_ = osmessage_;
        } else {
          result.osmessage_ = osmessageBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages) {
          return mergeFrom((no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages other) {
        if (other == no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages.getDefaultInstance()) return this;
        if (osmessageBuilder_ == null) {
          if (!other.osmessage_.isEmpty()) {
            if (osmessage_.isEmpty()) {
              osmessage_ = other.osmessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOsmessageIsMutable();
              osmessage_.addAll(other.osmessage_);
            }
            onChanged();
          }
        } else {
          if (!other.osmessage_.isEmpty()) {
            if (osmessageBuilder_.isEmpty()) {
              osmessageBuilder_.dispose();
              osmessageBuilder_ = null;
              osmessage_ = other.osmessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
              osmessageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOsmessageFieldBuilder() : null;
            } else {
              osmessageBuilder_.addAllMessages(other.osmessage_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getOsmessageCount(); i++) {
          if (!getOsmessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder subBuilder = no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOsmessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protobuf.OsMessage osmessage = 1;
      private java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> osmessage_ =
        java.util.Collections.emptyList();
      private void ensureOsmessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          osmessage_ = new java.util.ArrayList<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage>(osmessage_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> osmessageBuilder_;
      
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> getOsmessageList() {
        if (osmessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(osmessage_);
        } else {
          return osmessageBuilder_.getMessageList();
        }
      }
      public int getOsmessageCount() {
        if (osmessageBuilder_ == null) {
          return osmessage_.size();
        } else {
          return osmessageBuilder_.getCount();
        }
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage getOsmessage(int index) {
        if (osmessageBuilder_ == null) {
          return osmessage_.get(index);
        } else {
          return osmessageBuilder_.getMessage(index);
        }
      }
      public Builder setOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage value) {
        if (osmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOsmessageIsMutable();
          osmessage_.set(index, value);
          onChanged();
        } else {
          osmessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder builderForValue) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          osmessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOsmessage(no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage value) {
        if (osmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOsmessageIsMutable();
          osmessage_.add(value);
          onChanged();
        } else {
          osmessageBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage value) {
        if (osmessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOsmessageIsMutable();
          osmessage_.add(index, value);
          onChanged();
        } else {
          osmessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOsmessage(
          no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder builderForValue) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.add(builderForValue.build());
          onChanged();
        } else {
          osmessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOsmessage(
          int index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder builderForValue) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          osmessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOsmessage(
          java.lang.Iterable<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage> values) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          super.addAll(values, osmessage_);
          onChanged();
        } else {
          osmessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOsmessage() {
        if (osmessageBuilder_ == null) {
          osmessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          osmessageBuilder_.clear();
        }
        return this;
      }
      public Builder removeOsmessage(int index) {
        if (osmessageBuilder_ == null) {
          ensureOsmessageIsMutable();
          osmessage_.remove(index);
          onChanged();
        } else {
          osmessageBuilder_.remove(index);
        }
        return this;
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder getOsmessageBuilder(
          int index) {
        return getOsmessageFieldBuilder().getBuilder(index);
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder getOsmessageOrBuilder(
          int index) {
        if (osmessageBuilder_ == null) {
          return osmessage_.get(index);  } else {
          return osmessageBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
           getOsmessageOrBuilderList() {
        if (osmessageBuilder_ != null) {
          return osmessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(osmessage_);
        }
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder addOsmessageBuilder() {
        return getOsmessageFieldBuilder().addBuilder(
            no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance());
      }
      public no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder addOsmessageBuilder(
          int index) {
        return getOsmessageFieldBuilder().addBuilder(
            index, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.getDefaultInstance());
      }
      public java.util.List<no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder> 
           getOsmessageBuilderList() {
        return getOsmessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder> 
          getOsmessageFieldBuilder() {
        if (osmessageBuilder_ == null) {
          osmessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder, no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessageOrBuilder>(
                  osmessage_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          osmessage_ = null;
        }
        return osmessageBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.OsMessages)
    }
    
    static {
      defaultInstance = new OsMessages(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.OsMessages)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_OsMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_OsMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_OsMessages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_OsMessages_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010os.proto\022\010protobuf\"\032\n\007Request\022\017\n\007reque" +
      "st\030\001 \002(\t\")\n\tOsMessage\022\014\n\004name\030\001 \002(\t\022\016\n\006s" +
      "ystem\030\002 \002(\014\"4\n\nOsMessages\022&\n\tosmessage\030\001" +
      " \003(\0132\023.protobuf.OsMessageB7\n,no.mesan.mi" +
      "niprosjekt.kommunikasjon.protobufB\007OsPro" +
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Request_descriptor,
              new java.lang.String[] { "Request", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.Request.Builder.class);
          internal_static_protobuf_OsMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_OsMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_OsMessage_descriptor,
              new java.lang.String[] { "Name", "System", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessage.Builder.class);
          internal_static_protobuf_OsMessages_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protobuf_OsMessages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_OsMessages_descriptor,
              new java.lang.String[] { "Osmessage", },
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages.class,
              no.mesan.miniprosjekt.kommunikasjon.protobuf.OsProto.OsMessages.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
